# 1) Hotel Revenue Analysis
# Write a SQL query to calculate the total revenue generated by each hotel 
# for the month of July. Include the hotel name, city, and the total revenue 
# generated. Order the results in descending order of total revenue.
select 
    h.property_name, 
    h.city, 
    round(sum(revenue_generated)/1000000, 2) as total_revenue_mil
from fact_bookings b
join dim_hotels h 
    on b.property_id = h.property_id
where booking_id like "%Jul%"
group by h.property_name, h.city
order by total_revenue_mil desc
limit 5;

# 2) Occupancy Rate Calculation
# Write a SQL query to calculate the occupancy rate for each room type 
# in the "Luxury" category hotels for the month of June. The occupancy rate 
# is defined as the total number of booked room nights divided by the total 
# available room nights for each room type. Include the room type, hotel name, 
# and the occupancy rate. Order the results by the occupancy rate in descending order.
select 
    h.property_name, 
    h.category,
    round(count(booking_id)*100/(select sum(capacity) from fact_aggregated_bookings), 2)
		as occupancy_pct
from fact_bookings b
join dim_hotels h
    on b.property_id = h.property_id
where booking_id like "%Jun%" and h.category = "Luxury"
group by h.property_name, h.category
order by occupancy_pct desc;

# 3) Booking Channel Analysis
# Write a SQL query to analyze the distribution of booking platforms used by 
# customers for the "Premium" room category across all hotels. Calculate the 
# percentage distribution of each booking platform (e.g., Online Travel Agencies, 
# Hotel Website, Direct Booking, etc.) for the "Premium" room category. 
# Include the room category, booking platform, and the percentage distribution. 
# Order the results by the percentage distribution in descending order.
select 
    booking_platform,
    r.room_class, 
    round(count(booking_id)*100/(select count(booking_id) from fact_bookings), 2) 
		as dis_pct
from fact_bookings b
join dim_rooms r
    on r.room_id = b.room_category
where room_class = "Premium"
group by b.booking_platform, r.room_class
order by dis_pct desc;

# 4) Revenue and Occupancy Analysis
# Write a SQL query to calculate the average revenue per available room 
# (RevPAR) for each hotel in the "Luxury" category for the month of May. 
# RevPAR is defined as the total revenue generated from room bookings divided by 
# the total available room nights (revenue/capacity). Include the hotel name, city, and the 
# calculated RevPAR. Order the results in descending order of RevPAR.
select 
	h.property_name, 
    h.city,
    round((sum(revenue_generated))/(select sum(capacity) from fact_aggregated_bookings), 2)
    as RevPAR
from fact_bookings b
join dim_hotels h
    on h.property_id = b.property_id
where booking_id like "%May%" and category = "Luxury"
group by h.property_name, h.city
order by RevPar desc;
